[package]
name = "minitools"
version = "0.1.0"
edition = "2024"
default-run = "minitools"

[[bin]]
name = "b64"
required-features = ["b64"]
path = "src/bin/b64.rs"

[[bin]]
name = "bcrypt"
required-features = ["bcrypt"]
path = "src/bin/bcrypt.rs"

[[bin]]
name = "pngc"
required-features = ["pngc"]
path = "src/bin/pngc.rs"

[[bin]]
name = "dupfinder"
required-features = ["dupfinder"]
path = "src/bin/dupfinder.rs"

[dependencies]
base64 = { version = "0.22", optional = true }
bcrypt = { version = "0.17", optional = true }
eframe = { version = "0.32", optional = true }
glob = { version = "0.3", optional = true }
rfd = { version = "0.15", optional = true }
sha2 = { version = "0.10", optional = true }

[features]
b64 = ["dep:base64"]
bcrypt = ["dep:bcrypt"]
pngc = ["dep:eframe", "dep:rfd"]
dupfinder = ["dep:glob", "dep:sha2"]

# workspace settings
[workspace]
members = ["oxipng-gui", "ffmerge", "rnmd", "bdown", "hasher"]

[workspace.dependencies]
rfd = "0.15"
eframe = "0.32"
rayon = "1.10"
image = "0.25"
walkdir = "2.5"
md-5 = "0.10"
sha2 = "0.10"
tokio = { version = "1.47", features = [
  "rt-multi-thread",
  "macros",
  "process",
] }
egui_extras = "0.32"
sha1 = "0.10"
blake3 = "1.8"
oxipng = { version = "9.1", default-features = false, features = [
  "parallel",
  "filetime",
] }
num_cpus = "1.17"
uuid = { version = "1.18", features = ["v4"] }

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = "s"
strip = true
panic = "abort"
