[package]
name = "hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe.workspace = true
egui_extras.workspace = true
image.workspace = true
md-5.workspace = true
rfd.workspace = true
sha1.workspace = true
sha2.workspace = true
sys-locale.workspace = true

[build-dependencies]
embed-resource.workspace = true
